language: ruby
sudo: false
rvm:
  - 2.2
script:
  - bundle
#  - rake test
#branches:
#  only:
#  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
before_install:
  - git clone https://github.com/Freifunk-Dresden/Blog.git ../Blog/
#after_success:
#  - curl http://5.104.107.226/deploy
