# Site settings
title: Freifunk Dresden
tagline: das freie WLAN-Netzwerk für Dresden und Umgebung
description: > # this means to ignore newlines until "baseurl:"
 Freifunk Dresden ist eine lokale nicht-kommerzielle Initiative mit dem Ziel, ein WLAN-Netzwerk über Dresden aufzuspannen und freien Internetzugang anzubieten.
keywords: "freifunk,ff,dresden,freifunk-dresden,ffdd,freifunk-netz,freifunk-communties,verein,rosenwerk,wiki,forum,free-wifi,wifi,wlan,non-commercial,decentralize,dezentral,dezentralisiert,network,netzwerk,mesh,meshnet,meshnetz,meshnetwork,openwrt,nogluon,guestnetwork,gaestenetzwerk,buergernetz,gemeinschaftlich,bmxd,fastd,wireguard,maps,meshviewer,hopglass,grafana,community,communities,freifunk-freiberg,freiberg,freifunk-freital,freital,freifunk-meißen,meißen,freifunk-oberlausitz,oberlausitz,freifunk-pirna,pirna,freifunk-radebeul,radebeul,freifunk-tharandt,tharandt,freifunk-waldheim,waldheim"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.freifunk-dresden.de" # the base hostname & protocol for your site

excerpt_separator: <!--*-->
permalink: "news/:year/:month/:day/:title"

paginate_path: "/news/page:num/"
paginate: 10

plugins:
  - jekyll-paginate
  - jekyll-redirect-from

# Build settings
markdown: kramdown
exclude: [vendor]


# Community and Site Informations
community:
  # Metadata
  name: 'Dresden'
  meta: 'Freifunk Dresden'
  country: 'DE'
  address_postbox: 'Postfach 28 01 21'
  address_zipcode: '01141 Dresden'

  # Mail Contacts
  mail_info: 'info@freifunk-dresden.de'
  mail_lists: 'newsletter@freifunk-dresden.de'
  mail_lists_request: 'newsletter-request@freifunk-dresden.de'
  mail_vorstand: 'vorstand@freifunk-dresden.de'
  mail_spenden: 'spenden@freifunk-dresden.de'
  mail_datenschutz: 'datenschutz@freifunk-dresden.de'

  # Other Contacts
  github: 'Freifunk-Dresden'
  matrix: '#ffdd:envs.net'
  fediverse: 'ffdd'
  facebook: 'FreifunkDresden'
  twitter: 'ddmesh'
  instagram: 'freifunkdresden'

  url_mailinglist_newsletter: 'https://lists.freifunk-dresden.de/listinfo/newsletter'
  url_mailinglist_tech: 'https://lists.freifunk-dresden.de/listinfo/tech'
  url_chat: 'https://chat.freifunk-dresden.de/'
  url_blog: 'https://github.com/Freifunk-Dresden/Blog#freifunk-dresden-blog'
  url_forum: 'https://forum.freifunk.net/c/community/dresden'
  url_kalender: 'https://teamup.com/ks7edwt5ey8j8tvgpf'
  url_faq: 'https://wiki.freifunk-dresden.de/index.php/Fragen_und_Antworten_(FAQ)'

  url_wiki:  'https://wiki.freifunk-dresden.de/index.php/Hauptseite'
  url_doku: 'https://wiki.freifunk-dresden.de/index.php/Dokumentation'
  url_server: 'https://wiki.freifunk-dresden.de/index.php/Server'
  url_backbones: 'https://wiki.freifunk-dresden.de/index.php/Freifunk_Netzwerk'
  url_dienste: 'https://wiki.freifunk-dresden.de/index.php/Freifunkdienste'

  url_api: 'https://api.freifunk-dresden.de/'
  url_nodelist: 'https://wiki.freifunk-dresden.de/index.php/Hotspots'
  url_netgraph: 'https://grafana.freifunk-dresden.de/'
  url_map_gmaps: 'https://maps.freifunk-dresden.de/gmaps/'
  url_map_meshviewer: 'https://meshviewer.freifunk-dresden.de/'

  # Sprechstunde / Treffen
  url_online-sprechstunde: 'https://talk.freifunk-dresden.de/sprechstunde'
  url_sprechstunde: 'https://wiki.freifunk-dresden.de/index.php/Freifunk-Sprechstunde'
  url_treffenthema: 'https://wiki.freifunk-dresden.de/index.php/Sprechstunden-Themen'
  url_treffenort: 'https://www.openstreetmap.org/node/3140655489#map=13/51.0504/13.7274'
  url_ronwlan: 'http://10.200.4.180.freifunk-dresden.de/'

  # Router Links
  url_firmware: 'https://download.freifunk-dresden.de/'
  url_router: 'https://wiki.freifunk-dresden.de/index.php/Router'
  url_routerconf: 'anleitung-firmware-einspielen.pdf'
  url_routerconf_ext: 'https://wiki.freifunk-dresden.de/index.php/Router_einrichten'
  url_offloaderconfig: 'https://wiki.freifunk-dresden.de/index.php/Offloader_Konfiguration'
  url_routerpos: 'https://wiki.freifunk-dresden.de/index.php/Aufstellen'
  url_routerquote: 'https://www.heise.de/preisvergleich/?cat=WL-617380&sort=p'

  # Statistik
  url_stat-clients: 'https://grafana.freifunk-dresden.de/render/d-solo/geeqdF6mk/general-stats?orgId=1&refresh=5m&from=now-7d&to=now&theme=light&panelId=10&width=1000&height=500&tz=Europe%2FBerlin'
  url_stat-trafwan: 'https://grafana.freifunk-dresden.de/render/d-solo/geeqdF6mk/general-stats?orgId=1&refresh=5m&from=now-7d&to=now&theme=light&panelId=24&width=1000&height=500&tz=Europe%2FBerlin'
  url_stat-trafback: 'https://grafana.freifunk-dresden.de/render/d-solo/geeqdF6mk/general-stats?orgId=1&refresh=5m&from=now-7d&to=now&theme=light&panelId=25&width=1000&height=500&tz=Europe%2FBerlin'
  url_stat-trafovpn: 'https://grafana.freifunk-dresden.de/render/d-solo/geeqdF6mk/general-stats?orgId=1&refresh=5m&from=now-7d&to=now&theme=light&panelId=26&width=1000&height=500&tz=Europe%2FBerlin'

  # Verein
  # e.V. Docs
  doc_satzung: 'https://github.com/Freifunk-Dresden/Dokumente/raw/master/Verein/Satzung_Freifunk_Dresden.pdf'
  doc_ordnung: 'https://github.com/Freifunk-Dresden/Dokumente/raw/master/Verein/Beitragsordnung_Freifunk_Dresden.pdf'
  # Vorstand
  vorstand:
    - 'Mirko Tomaschek (Vorstandsvorsitzender)'
    - 'Diego Jahn (stellvertretender Vorsitzender)'
    - 'Michael Bauschke (Schatzmeister)'
    - 'Torsten Rudolph (Beisitzer)'

  # Sub Communities
  sub_com:
    - 'Freifunk Dresden'
    - 'Freifunk Freiberg'
    - 'Freifunk Freital'
    - 'Freifunk Oberlausitz (O.L.)'
    - 'Freifunk Pirna'
    - 'Freifunk Radebeul'
    - 'Freifunk Tharandt'


  # Projects
  projects:
    - name: 'Freifunk'
      desc: '<a href="https://wiki.freifunk-dresden.de/index.php/Gefl%C3%BCchtetenunterk%C3%BCnfte">Internet für Gefl&uuml;chtete</a>'

    - name: 'Freifunk Richtfunk'
      desc: '<a href="https://wiki.freifunk-dresden.de/index.php/Richtfunk-Pirna">in Pirna</a>'

    - name: 'Freifunk Installation'
      desc: '<a href="https://wiki.freifunk-dresden.de/index.php/Adventureland">Adventureland</a> (Paintball)'

    - name: 'Freifunk Installation'
      desc: '<a href="https://wiki.freifunk-dresden.de/index.php/Elbhangfest">zum Elbhangfest</a>'


  # Supporting Members
  sup_member:
    - name: 'Maria Engert Service'
      link: 'http://service-me.de'

    - name: 'Ingenieurb&uuml;ro Bauschke'
      link: 'http://ing-bauschke.de'


  # Distributoren
  distributoren:
    - name: 'IT-Service Merkelt'
      link: 'https://it-service-merkelt.de/'
      desc: '<img width="230" alt="dist_header" src="https://it-service-merkelt.de/images/header.jpg">'

