source 'https://rubygems.org'

gem 'rake'
gem 'jekyll', '3.8.5'
gem 'jekyll-watch', '2.0.0'
gem 'jekyll-paginate'
gem 'jekyll-redirect-from'
gem 'activesupport', '4.2.11.1'
gem 'nokogiri', '1.9.1'
gem 'html-proofer' , '3.10.2'
